### ISSUE TITLE
Incorrect longitude/latitude scaling for message 27

### ISSUE THREAD

**Issue by prgbwt** [wpietri/simpleais#2]
First, thanks for your work on `simpleais`, it is quite useful.

I noticed that `simpleais` reports bad longitude/latitude values for message 27. The root cause appears to be that `_parse_lon`/`_parse_lat` [use](https://github.com/wpietri/simpleais/blob/master/simpleais/__init__.py#L498-L510) a scale factor of 4 (10^4) regardless of message type, which gives incorrect results for message 27. Message 27 longitude/latitude has a lower resolution (degrees/10) than other AIS message types (degrees/10000).

Excerpt from [the standard](https://www.itu.int/dms_pubrec/itu-r/rec/m/R-REC-M.1371-5-201402-I!!PDF-E.pdf):
![image](https://user-images.githubusercontent.com/26989040/202355891-69f7b76a-c929-48ff-bc81-926c09dc32f6.png)

Cheers

**Comment by wpietri** [comment]
Thanks, this should be fixed in #5.
